version: '3.7'

services:
  client-main:
    build:
      ./client-main
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.10
    environment:
      BOT_TOKEN: 1070945563:AAGVgR7KIF9V6rSHvAoETUgCtSk73omHyrU

  service-command:
    build:
      ./service-command
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.11
    environment:
      REGISTRY_SERVER: 172.21.0.150:8500

  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: "dcbot"
      MYSQL_ROOT_PASSWORD: "LTYlty0123"
    restart: unless-stopped
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.101
    volumes:
      - ./db/db:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
      - ./db/logs:/var/log/mysql

  consul1:
    image: consul
    container_name: consul-1
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.150
    command: agent -server -bootstrap-expect=1 -node=consul-1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
  consul-ui:
    image: consul
    container_name: consul-2
    command: agent -retry-join=consul-1 -node=consul-2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - 8500:8500
    depends_on:
      - consul1
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.151
networks:
  dcbot-network:
    external: true