version: '3.7'

networks:
  dcbot-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  client-main:
    build:
      ./client-main
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.10
    environment:
      BOT_TOKEN: 1070945563:AAGVgR7KIF9V6rSHvAoETUgCtSk73omHyrU
      REGISTRY_SERVER: consul1:8500
  service-command:
    build:
      ./service-command
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.11
    environment:
      REGISTRY_SERVER: etcd1:8500
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: LTYlty0123

  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: dcbot
      MYSQL_ROOT_PASSWORD: lty01234
    networks:
      dcbot-network:
        ipv4_address: 172.21.0.101
    volumes:
      - ./db/db:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
      - ./db/logs:/var/log/mysql

  etcd1:
    image: quay.io/coreos/etcd
    container_name: etcd1
    command:
      /usr/local/bin/etcd
      -name etcd1
      -data-dir /etcd-data
      -advertise-client-urls http://0.0.0.0:2379
      -listen-client-urls http://0.0.0.0:2379
#      -initial-cluster-token blue-etcd-cluster
#      -initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
#      -initial-cluster-state new
    ports:
      - 2379
      - 2380
    networks:
      - dcbot-network



